import { Release, ChangeType } from "../types";

export const generateMarkdown = (releases: Release[]): string => {
  const header = `# Product Changelog\n\nGenerated by Changelog Pro\n\n`;

  const body = releases.map(release => {
    const dateStr = new Date(release.date).toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    });

    const breakingBadge = release.isBreaking ? ' **(BREAKING CHANGE)**' : '';
    
    // Group changes by type (Optional, but looks nicer) or just list them
    // Let's list them to preserve order, but formatted nicely.
    const changesList = release.changes.map(change => {
      const typeLabel = `[${change.type.toUpperCase()}]`;
      let changeBlock = `- **${typeLabel}** ${change.description}`;
      
      if (change.details) {
        // Indent details to nest them under the bullet point
        const indentedDetails = change.details
            .split('\n')
            .map(line => `  > ${line}`)
            .join('\n');
        changeBlock += `\n\n${indentedDetails}\n`;
      }
      
      return changeBlock;
    }).join('\n');

    return `## v${release.version} - ${release.title}
_${dateStr}_${breakingBadge}

> ${release.description}

### Changes
${changesList}
`;
  }).join('\n---\n\n');

  return header + body;
};

export const downloadChangelog = (releases: Release[]) => {
  const markdownContent = generateMarkdown(releases);
  const blob = new Blob([markdownContent], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `CHANGELOG-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};